### ISSUE TITLE
defining faces in the wrong direction can cause wrong ordering

### ISSUE THREAD

**Issue by undertrox** [origamimagiro/line-folder#1]
it is possible to create 2 .fold files that are exactly equal except for the order of the arrays inside faces_vertices (meaning the only difference is whether the faces are defined clockwise or counter-clockwise), where one of them is displayed correctly in linefolder and the other is not. 

In this zip file, there is an example of 2 such files, with the `_rev` file being the one that is displayed correctly. 
[foldedstates.zip](https://github.com/origamimagiro/line-folder/files/12064633/foldedstates.zip)

Both files are being displayed correctly on https://edemaine.github.io/fold/examples/foldviewer.html, which is why i assume the issue is not with the files

**Comment by origamimagiro** [comment]
Yeah, that seems like a bug. The flat-folder code expects something stronger than the FOLD spec: that faceOrder face indices are increasing, i.e., [f, g, o] has f < g, so my guess is the code doing the conversion is incorrect.

**Comment by origamimagiro** [comment]
The code handling faceOrder interpretation was definitely wrong (it was multiplying a boolean and an integer which is not advisable to say the least). I believe this should be fixed now.
